app = "get-education-backend"
primary_region = "sjc"

[build]

[env]
  APP_NAME = "GET Education Platform"
  DEBUG = "false"
  VERSION = "1.0.0"
  DATABASE_URL = "sqlite:///./data/get_education.db"
  DATABASE_URL_ASYNC = "sqlite+aiosqlite:///./data/get_education.db"
  SECRET_KEY = "production-secret-key-change-this"
  ALGORITHM = "HS256"
  ACCESS_TOKEN_EXPIRE_MINUTES = "30"
  UPLOAD_FOLDER = "uploads"
  MAX_FILE_SIZE = "10485760"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/health"

[vm]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512

[[mounts]]
  source = "get_education_data"
  destination = "/app/data"

[deploy]
  release_command = "mkdir -p data && python -c 'import asyncio; from app.database import init_db; asyncio.run(init_db())'"
