# render.yaml - Render deployment configuration
services:
  # Web Service
  - type: web
    name: language-ai-backend
    env: python
    plan: starter  # or standard for production
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app.main:app -w 2 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT --timeout 120 --preload
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: false
      - key: DATABASE_URL
        fromDatabase:
          name: language-ai-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: OPENAI_API_KEY
        sync: false  # Set manually in Render dashboard
      - key: REDIS_URL
        fromService:
          type: redis
          name: language-ai-redis
          property: connectionString
    
  # Redis Service
  - type: redis
    name: language-ai-redis
    plan: starter
    maxmemoryPolicy: allkeys-lru

# Database
databases:
  - name: language-ai-db
    plan: starter  # or standard for production