# render.yaml - Native Python deployment (alternative to Docker)
# This file tells Render how to deploy your app without Docker

services:
  - type: web
    name: language-ai-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m gunicorn app.main:app --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envVars:
      - key: DEBUG
        value: false
      - key: APP_NAME
        value: Language Learning AI Backend
      - key: SECRET_KEY
        generateValue: true
    scaling:
      minInstances: 1
      maxInstances: 3

# Optional: Add PostgreSQL database
databases:
  - name: language-ai-db
    databaseName: language_ai
    user: language_ai_user